name = "misionlunar"
compatibility_date = "2026-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "misionlunar-db"
database_id = "4d53262e-2a4a-4ccf-8c76-db595ce09642"
